# Generated by Django 4.0.4 on 2022-05-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_contact_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
